#!/bin/sh
dir="`dirname "$0"`"

TYPE="const harkd_test_t"
OUTH=$dir/tests.h
OUTL=$dir/tests.lst

echo "[+] Searching new `test` definitions ..."
echo -n "" > OUTL
for f in $dir/*.c;do
    sed -n 's|^$TYPE \([a-zA-Z0-9_][a-zA-Z0-9_]*\) = .*|\1|pg' $f >> $OUTL
done
cat $OUTL


echo "[+] Generating $OUTH ..."
echo "/* Generated by \`devices.h\`... */"                 > $OUTH
for n in `cat $dir/tests.lst`;do
    echo "extern const harkd_def_t $n;" >> $dir/devices.h
done
echo "const harkd_def_t *harkd_device_list[] = {"         >> $OUTH
for n in `cat $dir/tests.lst`;do echo "    &$n,"        >> $dir/devices.h; done
echo "    NULL"                                           >> $dir/devices.h
echo "};"                                                 >> $dir/devices.h
